<?xml version="1.0"?>
<authors>
  <year>1999</year>
  <author>
    <name>Joaquin Abellan</name>
    <email>jabellan@jet.es</email>
    <location>
      <country>
        <code>ES</code>
        <name>Spain</name>
      </country>
      <city>
        <name>Malaga</name>
        <latitude>36.716667</latitude>
        <longitude>-4.416667</longitude>
      </city>
      <university>
        <name>NA</name>
        <department>NA</department>
      </university>
    </location>
  </author>
  <author>
    <name>Serafin Moral</name>
    <email>smc@decsai.ugr.es</email>
    <location>
      <country>
        <code>ES</code>
        <name>Spain</name>
      </country>
      <city>
        <name>Granada</name>
        <latitude>37.183300</latitude>
        <longitude>-3.600000</longitude>
      </city>
      <university>
        <name>NA</name>
        <department>NA</department>
      </university>
    </location>
  </author>
  <author>
    <name>Stefan Arnborg</name>
    <email>stefan@nada.kth.se</email>
    <location>
      <country>
        <code>SE</code>
        <name>Sweden</name>
      </country>
      <city>
        <name>Stockholm</name>
        <latitude>59.333302</latitude>
        <longitude>18.049999</longitude>
      </city>
      <university>
        <name>NA</name>
        <department>NA</department>
      </university>
    </location>
  </author>
  <author>
    <name>Thomas Augustin</name>
    <email>thomas@stat.uni-muenchen.de</email>
    <location>
      <country>
        <code>DE</code>
        <name>Germany</name>
      </country>
      <city>
        <name>Munich</name>
        <latitude>48.150002</latitude>
        <longitude>11.583300</longitude>
      </city>
      <university>
        <name>NA</name>
        <department>NA</department>
      </university>
    </location>